version: "3.7"

services:
  api:
    image: ghcr.io/emlagowski/hack4good-server:0.9
    environment:
      VIRTUAL_HOST: ${API_DOMAINS:-api.hack4good.pl}
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: ${API_DOMAINS:-api.hack4good.pl}
    networks:
      - reverse_proxy

  web:
    image: ghcr.io/emlagowski/hack4good:0.6
    environment:
      NODE_ENV: PROD
      VIRTUAL_HOST: ${WEB_DOMAINS:-hack4good.pl,www.hack4good.pl}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${WEB_DOMAINS:-hack4good.pl,www.hack4good.pl}
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    name: reverse_proxy